---
# tasks file for revenni.docker

- name: install docker | repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: install docker | docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker

- name: install docker | packages
  apt:
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-docker
