---
# tasks file for revenni.docker

- name: install docker | repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: install docker | docker repo
  template:
    src: docker_repo.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'
    owner: root
    group: root

- name: install docker | packages
  apt:
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-docker
